services:
  app:
    #build:
      #context: ./   #builds the docker image from Dockerfile in current directory
      #dockerfile: Dockerfile
    image: stiebo/aiutilities:0.0.1
    env_file:
      .env
    environment:
      - OPENAI_API_KEY
      - DB_USER
      - DB_PASSWORD
      - SERVER_SERVLET_CONTEXT_PATH=/aiutilities  # set to nginx path
    ports:
      - "28857:28857"
    depends_on:
      - pgvector
    networks:
      - app-network
    #restart: always


  pgvector:
    image: 'pgvector/pgvector:pg16'
    env_file:
      .env
    environment:
      - POSTGRES_DB=aiutilities
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    #restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
